dist: xenial

language: python

python:
  - "3.7"

services:
  - mysql
  - docker

cache: pip

install:
  - pip install -r requirements.txt

script:
  - echo "skipping tests"

deploy:
  - provider: script
    script: bash ./docker-deploy.sh master
    on:
      branch: master

  - provider: script
    script: bash ./docker-deploy.sh api
    on:
      branch: api

  - provider: script
    script: bash ./docker-deploy.sh develop
    on:
      branch: develop